[package]
name = "allocator"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mmap = "0.1.1"

[dev-dependencies]
procinfo = "0.4.2"
