name: build

on: [push, pull_request]

env:
  CI: "1"

# Taken from https://github.com/swc-project/swc/blob/master/.github/workflows/cargo.yml

jobs:
  lint-buffer-pool:
    name: fmt
    runs-on: ubuntu-latest
    env:
      CRATE: buffer-pool
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Install stuff
        run: rustup component add rustfmt clippy
      - name: Run cargo clippy
        run: cd $CRATE && cargo clippy -- -Dwarnings
      - name: Run cargo fmt
        run: cd $CRATE && cargo fmt --all -- --check

  test-buffer-pool:
    name: test
    runs-on: ubuntu-latest
    env:
      CRATE: buffer-pool
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init

      # Ensure that all components all compilable.
      - name: Run cargo check for all targets
        run: cd $CRATE && cargo check --color always --all --all-targets

      - name: Run cargo test
        run: cd $CRATE && cargo test --color always --all

  lint-table:
    name: fmt
    runs-on: ubuntu-latest
    env:
      CRATE: table
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Install stuff
        run: rustup component add rustfmt clippy
      - name: Run cargo clippy
        run: cd $CRATE && cargo clippy -- -Dwarnings
      - name: Run cargo fmt
        run: cd $CRATE && cargo fmt --all -- --check

  test-table:
    name: test
    runs-on: ubuntu-latest
    env:
      CRATE: table
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init

      # Ensure that all components all compilable.
      - name: Run cargo check for all targets
        run: cd $CRATE && cargo check --color always --all --all-targets

      - name: Run cargo test
        run: cd $CRATE && cargo test --color always --all
